int_libs = # Interface dependencies.
imp_libs = # Implementation dependencies.
#import imp_libs += libhello%lib{hello}

lib{json}: $include_dir/hxx{**} $imp_libs $int_libs

# Build options.
#
cxx.poptions =+ "-I$include_dir" "-I$out_base" "-I$srcbase"

# Export options.
#
lib{json}:
{
  cxx.export.poptions =  "-I$include_dir" "-I$out_base" "-I$src_base"
  cxx.export.libs = $int_libs
}

# Install into the json/ subdirectory of, say, /usr/include/
# recreating subdirectories.
#
{hxx ixx txx}{*}:
{
  install         = include/nlohmann/
  install.subdirs = true
}

# TODO: find a better way to do this.
../upstream/single_include/nlohmann/
{
  {hxx ixx txx}{*}:
  {
    install         = include/nlohmann/
    install.subdirs = true
  }
}
